version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
      - image: circleci/postgres:10.2-alpine
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: postgres
          - POSTGRES_DB: tuxum_test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix ecto.setup
      - run: mix test
