version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7
        environment:
          - MIX_ENV: test
      - image: circleci/postgres:10.2-alpine
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: postgres
          - POSTGRES_DB: tuxum_test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - restore_cache:
          keys:
            - v1-deps-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-deps-cache-{{ .Branch }}
            - v1-deps-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-deps-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-deps-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-deps-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run: mix test
